SPP400/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views import generic
from django.shortcuts import redirect, render


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    url(r'^$', generic.RedirectView.as_view(url='/homepage/', permanent=False)),
    path('procedures/', include('procedures.urls')),
    path('patients/', include('patients.urls')),
    path('errorpage/', include('errorpage.urls')),
    path('roadmaps/', include('roadmaps.urls')),
    path('analytics/', include('analytics.urls')),
    path('assigned/', include('assigned_procedures.urls'))
]

handler404 = 'errorpage.views.error'
handler500 = 'errorpage.views.error'

patients/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index),
    path('create/', views.new_patient),
    path('profile/', views.profile),
    path('profile/update/', views.update),
    path('profile/delete/', views.delete),
    path('profile/procedures/', views.procedures),
    path('profile/procedures/add_roadmap/', views.add_roadmap),
    path('profile/procedures/add_procedure/', views.add_procedure),
    path('profile/procedures/remove/', views.remove_pairs_from_patient),
    path('profile/flag/', views.flag_patient),
    path('profile/unflag/', views.unflag_patient),
    path('profile/check_procedures/', views.checkbox_submission),
]

roadmaps/models.py
from django.db import models
from procedures.models import Procedure


class Roadmap(models.Model):
    roadmap_name = models.CharField(max_length=100)
    est_days_to_complete = models.IntegerField(default=0)

    def __str__(self):
        return self.roadmap_name

    # timeFrame = days, weeks, months
    # number = number of days/weeks/months
    def add_time_estimate(self, numberOf, timeFrame):
        if timeFrame == "days":
            self.est_days_to_complete = numberOf
            self.save()
            return True
        elif timeFrame == "weeks":
            self.est_days_to_complete = int(numberOf) * 7
            self.save()
            return True

        else:
            return False

    @staticmethod
    def update_roadmap_name(new_roadmap_name, current_roadmap):  # pragma: no cover
        quiried_roadmap = Roadmap.objects.filter(id=current_roadmap.id)
        for roadmap in quiried_roadmap:
            roadmap.roadmap_name = new_roadmap_name


class RoadmapProcedureLink(models.Model):
    roadmap = models.ManyToManyField(Roadmap)
    procedure = models.ManyToManyField(Procedure)
    # TODO phase should only allow values between 1 & some decided upper bound
    phase = models.IntegerField(default=1)

    @classmethod
    def link_procedure_to_roadmap(cls, procedure, roadmap, phase):
        new_link = RoadmapProcedureLink.objects.create(phase=phase)
        new_link.roadmap.add(roadmap)
        new_link.procedure.add(procedure)
        new_link.save()

        return new_link

    @staticmethod
    def get_procedures_from_roadmap(searchRoadmap):
        quiried_roadmap = RoadmapProcedureLink.objects.filter(roadmap=searchRoadmap.id)
        procedure_phase_list = []
        for procedures in quiried_roadmap:
            proc_phase = procedures.phase
            proc_query = procedures.procedure.all()
            for proc_name in proc_query:
                procedure_phase_list.append((proc_name, proc_phase))
        return procedure_phase_list

    @staticmethod
    def remove_pair_from_roadmap(roadmap_id, procedure_id, phase_number):
        queried_pairs = RoadmapProcedureLink.objects.filter(roadmap=roadmap_id, procedure=procedure_id,
                                                            phase=phase_number)
        for item in queried_pairs:
            item.delete()

    @staticmethod
    def remove_all_pairs_from_roadmap(roadmap_id):
        queried_pairs = RoadmapProcedureLink.objects.filter(roadmap=roadmap_id)
        for item in queried_pairs:
            item.delete()

    @staticmethod
    def seperate_by_phase(roadmap_pairs):
        seperated_by_phase = {}

        for procedure, phase in roadmap_pairs:
            if phase in seperated_by_phase:
                seperated_by_phase[phase].append(procedure)
            else:
                seperated_by_phase[phase] = [procedure]

        return seperated_by_phase
    
    @staticmethod
    def update_phase_for_procedure(current_roadmap, current_procedure, new_phase_number):  # pragma: no cover
        quiried_procedures = RoadmapProcedureLink.objects.filter(roadmap=current_roadmap.id,
                                                                 procedure=current_procedure.id)
        for procedure in quiried_procedures:
            procedure.phase = new_phase_number

roadmaps/forms.py
from django import forms
from django.forms import ModelForm
from roadmaps.models import RoadmapProcedureLink, Roadmap


class RoadmapForm(forms.Form):
    roadmap_name = forms.CharField(
        label='Roadmap Name',
        required=True,
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'id': 'roadmapName',
                'placeholder': "Enter Roadmap Name"
            }
        )
    )

    time = forms.IntegerField(
        label='Projected Timeline',
        widget=forms.NumberInput(
            attrs={
                'class': 'form-control',
                'id': 'procedureName',
                'placeholder': 'Enter Projected Completion Time'
            }
        )
    )

    CHOICES = [('days', 'Days'),
               ('weeks', 'Weeks')]

    time_frame = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect)


# Followed this to assign classes to these elements
# https://stackoverflow.com/questions/3679431/how-do-i-set-default-widget-attributes-for-a-django-modelform
class RoadmapProcedureLinkForm(ModelForm):
    # Add classes to the fields on initialization of the form
    def __init__(self, *args, **kwargs):
        super(RoadmapProcedureLinkForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            if 'class' in field.widget.attrs:
                field.widget.attrs['class'] += ' form-control'
            else:
                field.widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = RoadmapProcedureLink
        fields = ['procedure', 'phase']


class SelectFromRoadmap(forms.Form):
    roadmap = forms.ModelChoiceField(queryset=Roadmap.objects.all(),
                                     label='Roadmaps',
                                     widget=forms.Select(
                                         attrs={
                                             'class': 'form-control'
                                         }
                                     ))

patients/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from homepage.forms import VerifyActionForm
from patients.forms import NewPatient, SearchPatients, FlagForm
from procedures.models import Procedure
from roadmaps.forms import SelectFromRoadmap, RoadmapProcedureLinkForm
from patients.models import Patients
from assigned_procedures.models import AssignedProcedures
from roadmaps.models import RoadmapProcedureLink
from django.contrib import messages
import collections


@login_required
def index(request):
    if request.method == 'POST':
        form = SearchPatients(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            search = cd['search_terms']
            patients = []
            for patient in Patients.objects.all():
                if search.lower() in patient.first_name.lower() or search.lower() in patient.last_name.lower() or search.lower() in patient.record_number.lower() or patient.first_name.lower() in search.lower() or patient.last_name.lower() in search.lower() or patient.record_number.lower() in search.lower():
                    patients.append(patient)
            breadcrumbs = [('#', 'Patients')]
            return render(request, 'landing_page.html',
                          {'patients': patients, 'form': SearchPatients(), 'filter': cd['search_terms'],
                           'title': 'Patients', 'breadcrumbs': breadcrumbs})

    if request.method == 'GET':
        breadcrumbs = [('#', 'Patients')]
        return render(request, 'landing_page.html',
                      {'patients': Patients.objects.all(), 'form': SearchPatients(), 'title': 'Patients',
                       'breadcrumbs': breadcrumbs})


@login_required
def new_patient(request):
    if request.method == 'GET':
        breadcrumbs = [('/patients/', 'Patients'), ('#', 'New Patient')]
        return render(request, 'new_patient.html',
                      {'form': NewPatient(), 'title': 'New Patient', 'breadcrumbs': breadcrumbs})
    if request.method == 'POST':
        form = NewPatient(request.POST)
        if form.is_valid():
            # Clean form data and check that the username password pair is valid
            cd = form.cleaned_data
            patient = Patients.create_patient(cd['first_name'], cd['last_name'], cd['birth_date'], cd['record_number'],
                                              cd['referring_physician'], cd['date_of_referral'])
            patient.save()
            return redirect('/patients/')
        else:
            messages.error(request, 'Invalid Form!')
            return redirect('/patients/create/')


@login_required
def profile(request):
    if request.method == 'GET':
        try:
            # Get desired patient id from url
            patient = Patients.objects.get(id=request.GET.get('id'))
            breadcrumbs = [('/patients/', 'Patients'),
                           ('#', patient.last_name + ', ' + patient.first_name)]


            roadmap_pairs = AssignedProcedures.get_all_procedures(patient)

            all_assigned_procedures = RoadmapProcedureLink.seperate_by_phase(roadmap_pairs)

            first_incomplete_phase = AssignedProcedures.get_first_incomplete_phase(patient)

            ordered = collections.OrderedDict()
            phase_order = sorted(all_assigned_procedures.keys())
            for phase in phase_order:
                ordered[phase] = all_assigned_procedures[phase]
            all_assigned_procedures = ordered
            bool_goals = True
            try:
                goals = all_assigned_procedures[phase_order[-1]]
            except IndexError:
                goals = []
                bool_goals = False
            return render(request, 'patient.html',
                          {"patient": patient, 'title': 'Profile: ' + patient.last_name + ', ' + patient.first_name,
                           'breadcrumbs': breadcrumbs, 'assigned_procedures': all_assigned_procedures,
                           'flag_form': FlagForm(), 'goals': goals, 'bool_goals': bool_goals,
                           'first_incomplete_phase': first_incomplete_phase})
        except Patients.DoesNotExist:
            messages.warning(request, "The patient you tried to reach doesn't exist!")
            return redirect('/patients/')


@login_required
def update(request):
    if request.method == 'GET':
        try:
            # Get desired patient id from url
            patient = Patients.objects.get(id=request.GET.get('id'))

            breadcrumbs = [('/patients/', 'Patients'),
                           ('/patients/profile/?id=' + str(patient.id), patient.last_name + ', ' + patient.first_name),
                           ('#', 'Update: ' + patient.last_name + ', ' + patient.first_name)]

            initial_form_dict = {'first_name': patient.first_name, 'last_name': patient.last_name,
                                 'record_number': patient.record_number,
                                 'birth_date': patient.bday, 'referring_physician': patient.referring_physician,
                                 'date_of_referral': patient.date_of_referral}

            page_title = 'Update: ' + patient.last_name + ', ' + patient.first_name

            return render(request, 'update_patient.html',
                          {'form': NewPatient(initial=initial_form_dict), 'patient': patient, 'title': page_title,
                           'breadcrumbs': breadcrumbs, 'verification_form': VerifyActionForm()})

        except Patients.DoesNotExist:
            messages.warning(request, "The patient you tried to reach doesn't exist!")
            return redirect('/patients/')
    if request.method == 'POST':
        form = NewPatient(request.POST)
        try:
            patient = Patients.objects.get(id=request.GET.get('id'))
            if form.is_valid():
                # Clean form data and check that the username password pair is valid
                cd = form.cleaned_data
                # Get desired patient id from url
                patient.first_name = cd['first_name']
                patient.last_name = cd['last_name']
                patient.record_number = cd['record_number']
                patient.bday = cd['birth_date']
                patient.referring_physician = cd['referring_physician']
                patient.date_of_referral = cd['date_of_referral']
                patient.save()
                return redirect("/patients/profile/?id=" + str(patient.id))
            else:
                messages.error(request, 'Invalid Form!')
                return redirect('/patients/profile/update/?id=' + str(patient.id))
        except Patients.DoesNotExist:
            messages.warning(request, "The patient you tried to reach doesn't exist!")
            return redirect('/patients/')


@login_required
def delete(request):
    if request.method == 'POST':
        form = VerifyActionForm(request.POST)
        try:
            # Get desired patient id from url
            patient = Patients.objects.get(id=request.GET.get('id'))
            if form.is_valid():
                cd = form.cleaned_data
                if patient.record_number == cd['item_name']:
                    patient_assignments = AssignedProcedures.objects.filter(patient=patient)

                    for assignment in patient_assignments:
                        assignment.delete()
                    patient.delete()
                    return redirect('/patients/')
                else:
                    messages.error(request, 'Incorrect patient MRN!')
                    return redirect('/patients/profile/update/?id=' + str(patient.id))
            else:
                messages.error(request, 'Invalid Form!2')
                return redirect('/patients/profile/update/?id=' + str(patient.id))
        except Patients.DoesNotExist:
            messages.warning(request, "The patient you tried to reach doesn't exist!")
            return redirect('/patients/')


@login_required
def procedures(request):
    if request.method == 'GET':
        try:
            # Get desired patient id from url
            patient = Patients.objects.get(id=request.GET.get('id'))

            roadmap_pairs = AssignedProcedures.get_all_procedures(patient)

            breadcrumbs = [('/patients/', 'Patients'),
                           ('/patients/profile/?id=' + str(patient.id), patient.last_name + ', ' + patient.first_name),
                           ('#', patient.first_name + " " + patient.last_name + "'s  Procedures")]

            page_title = patient.first_name + " " + patient.last_name + "'s  Procedures"

            return render(request, 'patient_procedures.html',
                          {'roadmap_form': SelectFromRoadmap(),
                           'procedure_phase_form': RoadmapProcedureLinkForm(),
                           'patient': patient,
                           'breadcrumbs': breadcrumbs,
                           'title': page_title,
                           'roadmap_pairs': roadmap_pairs})
        except Patients.DoesNotExist:
            messages.warning(request, "The patient you tried to reach doesn't exist!")
            return redirect('/patients/')


# TODO change request.session to getting the id from the url
@login_required
def add_roadmap(request):
    if request.method == 'POST':
        try:
            patient = Patients.objects.get(id=request.GET.get('id'))

            form = SelectFromRoadmap(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                roadmap = cd['roadmap']
                AssignedProcedures.add_roadmap_to_patient(roadmap, patient)
                return redirect('/patients/profile/procedures/?id=' + str(patient.id))
            else:
                messages.error(request, 'Invalid Form!')
                return redirect('/homepage/')
        except Patients.DoesNotExist:

patients/templates/landing_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% include "global_styles.html" %}
</head>

<body>

<!-- Div holding the entire page -->
<div class="wrapper">

    {% include "sidebar.html" %}

    <div id="content">

        {% include "menu_bar.html" %}

        <div class="container">
            <div class="row">
                <div class="col" id="patients-col">
                    <div class="container">
                        <form action="/patients/" method="POST"> {% csrf_token %}
                            <div class="row">
                                <div class="col-sm-2">
                                    <h2>Patients</h2>
                                </div>
                                <div class="col-sm-8">
                                    <div class="row">
                                        <div class="float-left" align="left">
                                          {{ form.search_terms }}
                                        </div>
                                        <div class="float-left" align="right">
                                          <button type="submit" name="submit" class="btn btn-warning ml-3 mr-2 mb-4">Search</button>
                                        </div>
                                        {% if filter %}
                                          <div>
                                          <strong class="ml-2">Showing results for search: </strong> {{ filter }}
                                          </div>
                                        {% else %}
                                          <div>
                                          <a class="ml-2">Showing all patients. </a>
                                          </div>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <a class="btn btn-success" href="create/" role="button" name="new-patient-button">Add New Patient</a>
                                </div>
                            </div>
                        </form>
                      {% if not patients %}
                        <div class="alert alert-danger" role="alert" style="margin-top:20px">
                            <strong>Error: </strong>No patients found.
                        </div>
                      {% else %}
                      <table class="table table-hover border">
                        <thead>
                          <tr>
                            <th>Last</th>
                            <th>First</th>
                            <th>Record Number</th>
                            <th>Profile</th>
                          </tr>
                        </thead>
                        <tbody style="overflow-y: scroll; height: 25px">
                        {% for patient in patients %}
                          <tr>
                            <td>{{patient.last_name}}</td>
                            <td>{{patient.first_name}}</td>
                            <td>{{patient.record_number}}</td>
                            <td>
                                <a class="text-primary" href="/patients/profile/?id={{patient.id}}">View Profile</a>
                            </td>
                          </tr>
                        {% endfor %}
                        </tbody>
                      </table>
                      {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

{% include "global_js.html" %}
<!-- Personal JS -->
<script src={% static "patients/patients.js" %}></script>
</body>
</html>

patients/templates/new_patient.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% include "global_styles.html" %}
</head>

<body>

<!-- Div holding the entire page -->
<div class="wrapper">

    {% include "sidebar.html" %}

    <div id="content">

        {% include "menu_bar.html" %}

        <div class="container">
            {% if failed_creation %}
                <div class="alert alert-danger" role="alert">
                    <strong>Form requirements not met!</strong> Try entering your patient information again.
                </div>
            {% endif %}
            <h2> New Patient </h2>
            <form action="" method="POST"> {% csrf_token %}
                <div class="form-group">
                    <label for="firstName" name="firstName">First Name</label>
                    {{ form.first_name }}
                </div>
                <div class="form-group">
                    <label for="lastName" name="lastName">Last Name</label>
                    {{ form.last_name }}
                </div>
                <div class="form-group">
                    <label for="recordNumber" name="recordNumber">Medical Record Number</label>
                    {{ form.record_number }}
                </div>
                <div class="form-group">
                    <label for="birthDate" name="birthDate">Birthday </label>
                    {{ form.birth_date }}
                </div>
                <div class="form-group">
                    <label for="referringPhysician" name="referringPhysician">Referring Physician</label>
                    {{ form.referring_physician }}
                </div>
                <div class="form-group">
                    <label for="dateOfReferral" name="dateOfReferral">Date of Referral</label>
                    {{ form.date_of_referral }}
                </div>
                <button type="submit" class="btn btn-warning" name="submit">Create New Patient</button>
            </form>
        </div>
    </div>

</div>



{% include "global_js.html" %}
<!-- Personal JS -->
<script src={% static "patients/patients.js" %}></script>
</body>
</html>

patients/templates/patient_procedures.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% include "global_styles.html" %}
</head>

<body>

<!-- Div holding the entire page -->
<div class="wrapper">

    {% include "sidebar.html" %}

    <div id="content">

        {% include "menu_bar.html" %}

        <div class="row">
            <div class="col">
                <form action="/patients/profile/procedures/add_procedure/?id={{ patient.id }}" method="POST"> {% csrf_token %}
                    <div class="form-group">
                        <label for="id_procedure">Procedures: </label>
                        {{ procedure_phase_form.procedure }}
                    </div>

                    <div class="form-group">
                        <label for="id_phase">Phase: </label>
                        {{ procedure_phase_form.phase }}
                    </div>
                    <button type="submit" class="btn btn-warning mb-4">Add Procedure(s) to Patient</button>
                </form>
            </div>
            <div class="col">

                <form action="/patients/profile/procedures/add_roadmap/?id={{ patient.id }}" method="post">{% csrf_token %}
                    <div class="container-fluid">
                        <label for="id_roadmap">Roadmaps: </label>
                        {{ roadmap_form.roadmap }}
                    </div>
                    <button type="submit" class="btn btn-warning my-4">Add Roadmap to Patient</button>
                </form>
            </div>
        </div>
        <div class="container-fixed">
            <form action="/patients/profile/procedures/remove/?id={{ patient.id }}" method="post">{% csrf_token %}
                <table class="table table-hover border">
                    <thead>
                    <tr>
                        <th scope="col">Procedure Name</th>
                        <th scope="col">Phase</th>
                        <th scope="col">Modify Item</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for procedure, phase in roadmap_pairs|dictsort:1 %}
                        <tr>
                            <td>{{ procedure.procedure_name }}</td>
                            <td>{{ phase }}</td>
                            <td><input type="checkbox" name="selection[]" value="{{ procedure.id }},{{ phase }}">
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <button type="button" class="btn btn-warning my-4" data-toggle="modal" data-target="#removePairs">
                    Remove Selected Pairs
                </button>
                <!-- Modal stuff goes here -->
                <div class="modal fade" id="removePairs" tabindex="-1" role="dialog"
                     aria-labelledby="removePairsLabel"
                     aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title" id="removePairsLabel">Remove Selected Pairs</h4>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <h5>Are you sure?</h5>
                            </div>
                            <div class="modal-footer">
                                <button type="submit" class="btn btn-danger mb-4">Removed Selected Pairs</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

</div>


{% include "global_js.html" %}
<!-- Personal JS -->
<script src={% static "patients/patients.js" %}></script>
</body>
</html>

patients/templates/update_patient.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% include "global_styles.html" %}
</head>

<body>

<!-- Div holding the entire page -->
<div class="wrapper">

    {% include "sidebar.html" %}

    <div id="content">

        {% include "menu_bar.html" %}

        <div class="container">
            {% if failed_creation %}
                <div class="alert alert-danger" role="alert">
                    <strong>Form requirements not met!</strong> Try entering your patient information again.
                </div>
            {% endif %}
            <h2> Update information for: {{ patient.first_name }} {{ patient.last_name }} </h2>
            <form action="/patients/profile/update/?id={{ patient.id }}" method="POST"> {% csrf_token %}
                <div class="form-group">
                    <label for="firstName">First Name</label>
                    {{ form.first_name }}
                </div>
                <div class="form-group">
                    <label for="lastName">Last Name</label>
                    {{ form.last_name }}
                </div>
                <div class="form-group">
                    <label for="recordNumber">Medical Record Number</label>
                    {{ form.record_number }}
                </div>
                <div class="form-group">
                    <label for="birthDate">Birthday </label>
                    {{ form.birth_date }}
                </div>
                <div class="form-group">
                    <label for="referringPhysician">Referring Physician</label>
                    {{ form.referring_physician }}
                </div>
                <div class="form-group">
                    <label for="dateOfReferral">Date of Referral</label>
                    {{ form.date_of_referral }}
                </div>
                <button type="submit" class="btn btn-warning mb-4">Update Patient</button>
            </form>


            <button type="button" class="btn btn-danger my-4" data-toggle="modal" data-target="#deletePatient">
                Delete Patient
            </button>
            <div class="modal fade" id="deletePatient" tabindex="-1" role="dialog" aria-labelledby="deletePatientLabel"
                 aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title" id="deletePatientLabel">Delete Patient</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <form action="/patients/profile/delete/?id={{ patient.id }}" method="POST"> {% csrf_token %}

                            <div class="modal-body">
                                <p>This action <strong>cannot</strong> be undone. This will permamantly delete
                                    the patient <strong>
                                        <ul><li>{{ patient.last_name }}, {{ patient.first_name }}</li>
                                            <li>MRN: {{ patient.record_number }}</li></ul></strong> from the system.
                                </p>

                                <p>Please type in the MRN of the patient to confirm.</p>
                                <div class="form-group">
                                    {{ verification_form.item_name }}
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="submit" class="btn btn-danger mb-4">Delete Patient</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>

</div>


{% include "global_js.html" %}
<!-- Personal JS -->
<script src={% static "patients/patients.js" %}></script>
</body>
</html>