SPP400/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views import generic
from django.shortcuts import redirect, render


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    url(r'^$', generic.RedirectView.as_view(url='/homepage/', permanent=False)),
    path('procedures/', include('procedures.urls')),
    path('patients/', include('patients.urls')),
    path('errorpage/', include('errorpage.urls')),
    path('roadmaps/', include('roadmaps.urls')),
    path('analytics/', include('analytics.urls')),
    path('assigned/', include('assigned_procedures.urls'))
]

handler404 = 'errorpage.views.error'
handler500 = 'errorpage.views.error'

homepage/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.log_in),
    path('logout/', views.log_out),
    #path('code/', views.new_code),
    path('authenticate/', views.authenticator),
    path('homepage/', views.homepage),
]

homepage/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
import random
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.mail import EmailMessage
from datetime import timedelta
from django.utils import timezone


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    key = models.IntegerField(default=1)
    key_expiration = models.DateTimeField(default=timezone.now)

    def new_key(self):
        user = self.user
        self.key = random.randint(10000000, 99999999)
        self.save()
        email = EmailMessage('New authentication key', "Your new authentication key is: " + str(self.key), to=[user.email])
        email.send()

    def check_key(self, num):
        if self.user.email is None:
            return True
        if self.key == num:
            self.key_expiration = timezone.now() + timedelta(days=30)
            return True
        else:
            return False

    def expired(self):
        if timezone.now() > self.key_expiration:
            return True
        else:
            return False


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        profile = Profile.objects.create(user=instance)
        instance.username = instance.username.lower()
        profile.save()
        instance.save()


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    if not instance.username == instance.username.lower():
        instance.username = instance.username.lower()
        instance.save()
    instance.profile.save()

homepage/forms.py
from django import forms


class LoginForm(forms.Form):

    username = forms.CharField(
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'id': 'loginUsername',
                'placeholder': 'Enter username'
            }
        ))
    password = forms.CharField(widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'id': 'loginPassword',
                'placeholder': 'Password'
            }
    ))

class VerifyActionForm(forms.Form):
    item_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'id': 'item-name',
        }
    ))

class NewKeyForm(forms.Form):
    username = forms.CharField(
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'id': 'newKeyUsername',
                'placeholder': 'Enter username'
            }
        ))


class AuthenticateForm(forms.Form):
    key = forms.IntegerField()

homepage/views.py
from django.shortcuts import render, redirect

from assigned_procedures.models import AssignedProcedures
from homepage.forms import LoginForm, NewKeyForm, AuthenticateForm
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from patients.models import Patients
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist


@login_required()
def homepage(request):
    if request.method == 'GET':
        return render(request, 'homepage.html', {'title':'Home', 'patients' : Patients.objects.all(), 'alert_patients': AssignedProcedures.update_and_return_all_patient_goal_flags()})


def log_in(request):
    # Login session cookies cleared for login, 'request.session.modified = True' saves it
    request.session['username'] = {}
    request.session['password'] = {}
    request.session.modified = True

    if request.method == 'GET':
        return render(request, 'login.html', {'form': LoginForm()})
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            # Clean form data and check that the username password pair is valid
            cd = form.cleaned_data
            cd['username'] = cd['username'].lower()
            user = authenticate(username=cd['username'], password=cd['password'])
            if user is not None:
                if user.profile.expired():
                    # Store username and password as cookies temporarily for two-factor
                    request.session['username'] = cd['username']
                    request.session['password'] = cd['password']
                    user.profile.new_key()
                    return render(request, 'authenticate.html', {'form': AuthenticateForm()}, status=200)
                else:
                    login(request, user)
                    return redirect('/homepage/')
            else:
                return render(request, 'login.html', {'form': LoginForm(), 'failed_login': True}, status=401)


def log_out(request):
    logout(request)
    return render(request, 'login.html', {'form': LoginForm(), 'logged_out': True})


'''
def new_code(request):
    if request.method == 'GET':
        return render(request, 'new_key.html', {'form': NewKeyForm(), 'failed_login': False, 'two_factor': True}, status=200)
    if request.method == 'POST':
        form = NewKeyForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            try:
                user = User.objects.get(username=cd['username'])
                user.profile.new_key()
                return render(request, 'login.html', {'form': LoginForm(), 'failed_login': False, 'two_factor': True}, status=200)

            except ObjectDoesNotExist:
                return render(request, 'new_key.html', {'form': NewKeyForm(), 'failed_login': False, 'two_factor': True}, status=200)
'''


def authenticator(request):
    if request.method == 'POST':
        user = authenticate(username=request.session['username'], password=request.session['password'])
        form = AuthenticateForm(request.POST)
        if form.is_valid():
            key = form.cleaned_data['key']
            if user.profile.check_key(key):
                login(request, user)
                request.session['username'] = {}
                request.session['password'] = {}
                request.session.modified = True
                return redirect('/homepage/')
            # this should cause an error to show up
            return render(request, 'authenticate.html', {'form': AuthenticateForm(), 'bad_code': True}, status=401)

homepage/templates/application.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" type="text/css" href={% static "homepage/login.css" %}>
    <title>Login Page</title>
</head>

<body>
{% block content %}

{% endblock %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>


</html>

homepage/templates/authenticate.html
{% extends 'application.html' %}
{% block content %}
<div class="container-fixed">
{% if bad_code %}
    <div class="alert alert-danger" role="alert">
    <strong>Invalid Code:</strong> Check you are using the most recent version.
    </div>
    {% else %}
    <p> </p>
    {% endif %}
    <h2> Enter your two-factor code sent to you by email. </h2>
    <form action="/authenticate/" method="POST"> {% csrf_token %}
        <div class="form-group">
            <label for="id_key"> Authentication Code</label>
            {{ form.key }}
        </div>
        <button type="submit" name="submit" class="btn btn-warning"> Submit</button>
    </form>
</div>
{% endblock %}

homepage/templates/global_js.html
{% block content %}
    {% load static %}
    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
            integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
            crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
            integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
            crossorigin="anonymous"></script>
    <!-- jQuery Custom Scroller CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src={% static "homepage/sidebar.js" %}></script>
{% endblock %}

homepage/templates/global_styles.html
{% block content %}
<meta charset="UTF-8">
    <!-- Helps scale for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Custom Scroll Bar -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
    {% load static %}
    <link rel="stylesheet" type="text/css" href={% static "homepage/sidebar.css" %}>
    <title>{{ title }}</title>
{% endblock %}

homepage/templates/login.html
{% extends 'application.html' %}
{% block content %}
<div class="container-fixed">
{% if failed_login %}
    <div class="alert alert-danger" role="alert">
    <strong>Invalid Login!</strong> Try entering your login information again.
    </div>
    {% endif %}
    <h2> Cardiology Patient Manager </h2>
    <form action="/login/" method="POST"> {% csrf_token %}
        <div class="form-group">
            <label for="loginUsername"> Username</label>
            {{ form.username }}
        </div>
        <div class="form-group">
            <label for="loginPassword"> Password</label>
            {{ form.password }}
        </div>
        <button type="submit" name="submit" class="btn btn-warning">Login</button>
    </form>
</div>
{% endblock %}

homepage/templates/menu_bar.html
{% block content %}
    {% load octicons %}
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <div class="container-fluid">
            <button type="button" id="sidebarCollapse" class="btn btn-info navbar-btn">
                    <span>
                        {% octicon "three-bars" %}
                        Menu
                    </span>
            </button>
        </div>
    </nav>

    {% if breadcrumbs %}
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                {% for url_string, name in breadcrumbs %}
                    {% if forloop.last %}
                        <li class="breadcrumb-item active" aria-current="page">{{ name }}</li>
                    {% else %}
                        <li class="breadcrumb-item"><a href="{{ url_string }}">{{ name }}</a></li>
                    {% endif %}
                {% endfor %}
            </ol>
        </nav>
    {% endif %}

    {% for message in messages %}
            <div class="alert alert-danger" role="alert">
            {% if message.tags == "error" %}
                <strong>{{ message }}</strong> Please try again.
            {% endif %}
            {% if message.tags == "warning" %}
                <strong>{{ message }}</strong>
            {% endif %}
            </div>
        {% endfor %}

{% endblock %}

homepage/templates/new_key.html
{% extends 'application.html' %}
{% block content %}
<div class="container-fixed">
{% if failed_login %}
    <div class="alert alert-danger" role="alert">
    <strong>Invalid Login!</strong> Try entering your login information again.
    </div>
    {% else %}
    <p> </p>
    {% endif %}
    <h2> Enter your username to receive a new two-factor code. </h2>
    <form action="/code/" method="POST"> {% csrf_token %}
        <div class="form-group">
            <label for="loginUsername"> Username</label>
            {{ form.username }}
        </div>
        <button type="submit" class="btn btn-warning"> E-Mail Code</button>
    </form>
</div>
{% endblock %}

homepage/templates/sidebar.html
<!-- Tutorial for creating sidebar can be found at: https://bootstrapious.com/p/bootstrap-sidebar -->
{% block content %}
    {% load octicons %}
    {% load static %}
    <nav id="sidebar">
        <div class="sidebar-header">
            <a class="navbar-brand" href="#">
                <img src="{% static "homepage/DomeWordLeft BLACK.png" %}" width="215px" alt="">
            </a>
        </div>

        <!-- This holds the bulk of the side bar -->
        <ul class="list-unstyled components">
            <p id="greeting">{{ user.username }}</p>
            <!-- .active is denoting that homepage is the active page -->

            <li id="home">
                <a href="/homepage/">
                    {% octicon "home" %}
                    Home
                </a>
            </li>


            <li id="patients">
                <a href="/patients/" name="patients">
                    {% octicon "organization" %}
                    Patients
                </a>
            </li>

            <li id="procedures">
                <a href="/procedures/" name="procedures">
                    {% octicon "pulse" %}
                    Procedures
                </a>
            </li>

            <li id="roadmaps">
                <a href="/roadmaps/">
                    {% octicon "repo" %}
                    Roadmaps
                </a>
            </li>

            <li id="analytic">
                <a href="/analytics/">
                    {% octicon "graph" %}
                    Analytics
                </a>
            </li>

            <!-- Profile list item -->
            <li id="profile">
                <!-- the <a> href must match the id of the <ul> that contains the drop down -->
                <a href="#profileSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    {% octicon "person" %}
                    Profile
                </a>
                <ul class="collapse list-unstyled" id="profileSubmenu">

                    <li style="display: none">
                        <a href="#">
                            {% octicon "gear" %}
                            Settings
                        </a>
                    </li>

                    <li>
                        <a href="/logout">
                            {% octicon "x" %}
                            Logout
                        </a>
                    </li>
                </ul>
            </li>


        </ul>


    </nav>
{% endblock %}